

### Search Pattern  ###

ubuntu@DolfinED:~$ cat file1.txt
Name      DEP     Salary
Nader    account   45000
Sara     account   25000
Mena     sales     50000
Ali      account   47000
Ahmed    sales     15000
deepak   sales     23000
Sara     sales     13000
Satvik   HR        80000





ubuntu@DolfinED:~$ awk ' BEGIN{ total=0 } { total+=$3 } END{ print "Total Salaries= ", total } ' file1.txt
Total Salaries=  298000

## Average Salary
ubuntu@DolfinED:~$ awk ' BEGIN{ total=0 ; total1=0 } { total+=$3; total1=total/NR } END{ print "Average Salaries= ", total1 } ' file1.txt
Average Salaries=  33111.1
