




ubuntu@DolfinED:~$ cat file1.txt
Nader    account   45000
Sara     account   25000
Mena     sales     50000
Ali      account   47000
Ahmed    sales     15000
deepak   sales     23000
Sara     sales     13000
Satvik   HR        80000




############# Script 1 #############


ubuntu@DolfinED:~$ vim for-awk.sh

---
#!/bin/bash

awk '{
    for (i = 1; i <= NF; i++) 
    {
        if (i == 3) 
        {
            sum += $i
        }
    }
}
END {
    print "Sum of Salaries is", sum
}' file1.txt
---

