
#at command for scheduling jobs to run in the future at a specific time for one time only
## Change the timezone

ubuntu@DolfinED:~$ date
Wed Sep 13 09:31:36 UTC 2023

ubuntu@DolfinED:~$ timedatectl list-timezones
Africa/Cairo


ubuntu@DolfinED:~$ sudo timedatectl set-timezone Africa/Cairo

ubuntu@DolfinED:~$ date
Wed Sep 13 12:31:56 EEST 2023




############# Script 1 #############

ubuntu@DolfinED:~$ vim at.sh
---
#!/bin/bash

mkdir file-at

touch file-at/test
---

### Run Script
ubuntu@DolfinED:~$ chmod +x at.sh
ubuntu@DolfinED:~$ at 10am 12/10/2025 -f at.sh
#-f mean read com

