

############# Script 1 #############

ubuntu@DolfinED:~$ vim sc7.sh
---
#!/bin/bash

read -p "Enter Your Name: " name
read -p "Enter Your Age: " age

echo

echo "Nice to meet you $name "
echo "Your Age is $age"
---

############# Script 2 #############

ubuntu@DolfinED:~$ vim sc7.sh
---
#!/bin/bash

#-t will wait 2 sec then run next command till the user enter the value
read -t 2 -p "Enter Your Name: " name
read -t 2 -p "Enter Your Age: " age

echo

echo "Nice to meet you $name "
echo "Your Age is $age"
---


############# Script 3 #############

ubuntu@DolfinED:~$ vim sc7.sh
---
#!/bin/bash
#-s will hide the input 
read -s -p "Enter Your Name: " name
read -sp "Enter Your Age: " age

echo

echo "Nice to meet you $name "
echo "Your Age is $age"
---
